### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by sudip70**
Full development along with documentation Final Merge

### CODE REVIEW

**Review by akajay07 — APPROVED** [review]
ready for the final merge

**Review by Shriyaupadhyay30 — COMMENTED** [review]
Looks great and clean.. Good to go with it

**Review by Shriyaupadhyay30 — APPROVED** [review]

**Review by Snehpathak — APPROVED** [review]
good to go!!!

**Comment by sudip70** [comment]
Merging

**Pull request merged**
